# Generated by Django 3.1.7 on 2021-03-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210315_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='lng',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.JSONField(null=True),
        ),
    ]
